theme = "kanagawa"

[editor]
end-of-line-diagnostics = "hint"
cursorline = true
rulers = [120]
bufferline = "multiple"
completion-trigger-len = 1
completion-timeout = 5

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = false
wrap-at-text-width = true

# [editor.lsp]
# display-inlay-hints = true

[keys.normal]
"ret" = "goto_word"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal.space]
q = ":bc"
Q.a = ":bca"
Q.o = ":bco"

[keys.select]
"ret" = "extend_to_word"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.insert]
C-backspace = "delete_word_backward"
