theme = "kanagawa"

[keys.normal]
"ret" = "goto_word"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal.space]
q = ":bc"

[keys.select]
"ret" = "extend_to_word"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.insert]
C-backspace = "delete_word_backward"

[editor]
end-of-line-diagnostics = "hint"
cursorline = true
rulers = [120]
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
bufferline = "multiple"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "┆"

# [editor.lsp]
# display-inlay-hints = true
