theme = "kanagawa"

[keys.normal]
"ret" = "goto_word"

[keys.select]
"ret" = "extend_to_word"

[keys.insert]
C-backspace = "delete_word_backward"

[editor]
end-of-line-diagnostics = "hint"
cursorline = true
rulers = [120]
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "┆"

[editor.lsp]
display-messages = true
# display-inlay-hints = true
