theme = "kanagawa"

[editor]
cursorline = true
rulers = [100]
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"
completion-trigger-len = 1
completion-timeout = 5

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = false
wrap-at-text-width = true

[keys.normal]
"ret" = "goto_word"

[keys.normal.space]
q = ":bc"
Q.a = ":bca"
Q.o = ":bco"
u = ":update"

[keys.select]
"ret" = "extend_to_word"

[keys.insert]
C-backspace = "delete_word_backward"
"C-[" = "normal_mode"
