[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.allFeatures = true

[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true

[language-server.python]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "markdown"
file-types = ["md", "markdown"]
soft-wrap.enable = true
text-width = 80
rulers = []

[[language]]
name = "c-sharp"
rulers = [100, 120]
